/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.itec1.e_commerce.views;

import com.itec1.e_commerce.entities.Client;
import com.itec1.e_commerce.controllers.ReportPanelController;
import com.itec1.e_commerce.views.resources.JTextFieldListener;
import com.itec1.e_commerce.views.resources.TableListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author sjcex
 */
public class Report_ProvidersPanel extends javax.swing.JPanel implements InterfacePanel, InterfaceOrderPanel {

    private final ReportPanelController panel;
    private List<Client> clients;
    private List<JLabel> lines = new ArrayList<>();

    /**
     * Creates new form Management_Client_Panel
     */
    public Report_ProvidersPanel() {
        initComponents();
        this.panel = new ReportPanelController(this);
        this.panel.updateClientsTable("");
        initListener();
        overviewReport();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel_data = new javax.swing.JPanel();
        jbl_reportTitle = new javax.swing.JLabel();
        jbl_reportDataLine1 = new javax.swing.JLabel();
        jbl_reportDataLine2 = new javax.swing.JLabel();
        jbl_reportDataLine3 = new javax.swing.JLabel();
        jbl_reportDataLine4 = new javax.swing.JLabel();
        jbl_reportDataLine5 = new javax.swing.JLabel();
        jbl_reportDataLine6 = new javax.swing.JLabel();
        jbl_reportDataLine7 = new javax.swing.JLabel();
        jbl_reportDataLine8 = new javax.swing.JLabel();
        jbl_reportDataLine9 = new javax.swing.JLabel();
        jbl_reportDataLine0 = new javax.swing.JLabel();
        jPanel_table = new javax.swing.JPanel();
        jScrollPaneTabla = new javax.swing.JScrollPane();
        tableClient = new javax.swing.JTable();
        deselectClient = new javax.swing.JButton();
        jbl_filter = new javax.swing.JLabel();
        jtf_cuitFilter = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(800, 600));
        jPanel2.setMinimumSize(new java.awt.Dimension(800, 600));

        jPanel_data.setBackground(new java.awt.Color(0, 51, 255));

        jbl_reportTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbl_reportTitle.setForeground(new java.awt.Color(255, 255, 255));
        jbl_reportTitle.setText("INFORME GENERAL:");

        jbl_reportDataLine1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbl_reportDataLine1.setForeground(new java.awt.Color(255, 255, 255));

        jbl_reportDataLine2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbl_reportDataLine2.setForeground(new java.awt.Color(255, 255, 255));

        jbl_reportDataLine3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbl_reportDataLine3.setForeground(new java.awt.Color(255, 255, 255));

        jbl_reportDataLine4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbl_reportDataLine4.setForeground(new java.awt.Color(255, 255, 255));

        jbl_reportDataLine5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbl_reportDataLine5.setForeground(new java.awt.Color(255, 255, 255));

        jbl_reportDataLine6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbl_reportDataLine6.setForeground(new java.awt.Color(255, 255, 255));

        jbl_reportDataLine7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbl_reportDataLine7.setForeground(new java.awt.Color(255, 255, 255));

        jbl_reportDataLine8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbl_reportDataLine8.setForeground(new java.awt.Color(255, 255, 255));

        jbl_reportDataLine9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbl_reportDataLine9.setForeground(new java.awt.Color(255, 255, 255));

        jbl_reportDataLine0.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbl_reportDataLine0.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel_dataLayout = new javax.swing.GroupLayout(jPanel_data);
        jPanel_data.setLayout(jPanel_dataLayout);
        jPanel_dataLayout.setHorizontalGroup(
            jPanel_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_dataLayout.createSequentialGroup()
                .addGroup(jPanel_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_dataLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jbl_reportTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_dataLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbl_reportDataLine2, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbl_reportDataLine1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbl_reportDataLine3, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbl_reportDataLine5, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbl_reportDataLine4, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbl_reportDataLine6, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbl_reportDataLine8, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbl_reportDataLine7, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbl_reportDataLine9, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbl_reportDataLine0, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_dataLayout.setVerticalGroup(
            jPanel_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_dataLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jbl_reportTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbl_reportDataLine1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbl_reportDataLine2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbl_reportDataLine3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbl_reportDataLine4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbl_reportDataLine5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbl_reportDataLine6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbl_reportDataLine7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbl_reportDataLine8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbl_reportDataLine9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbl_reportDataLine0, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        jPanel_table.setBackground(new java.awt.Color(0, 51, 255));

        jScrollPaneTabla.setMaximumSize(new java.awt.Dimension(950, 750));
        jScrollPaneTabla.setMinimumSize(new java.awt.Dimension(950, 750));
        jScrollPaneTabla.setPreferredSize(new java.awt.Dimension(950, 750));

        tableClient.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jScrollPaneTabla.setViewportView(tableClient);

        deselectClient.setText("DESELECCIONAR");
        deselectClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deselectClientActionPerformed(evt);
            }
        });

        jbl_filter.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbl_filter.setForeground(new java.awt.Color(255, 255, 255));
        jbl_filter.setText("Filtrar por cuit:");

        jtf_cuitFilter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtf_cuitFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_cuitFilterActionPerformed(evt);
            }
        });

        jLabel1.setText("Informe de Proveedores");

        javax.swing.GroupLayout jPanel_tableLayout = new javax.swing.GroupLayout(jPanel_table);
        jPanel_table.setLayout(jPanel_tableLayout);
        jPanel_tableLayout.setHorizontalGroup(
            jPanel_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_tableLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(deselectClient)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbl_filter, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_cuitFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
            .addGroup(jPanel_tableLayout.createSequentialGroup()
                .addGroup(jPanel_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_tableLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPaneTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_tableLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel_tableLayout.setVerticalGroup(
            jPanel_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_tableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbl_filter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtf_cuitFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(deselectClient, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel_table, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_data, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(320, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel_table, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_cuitFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_cuitFilterActionPerformed

    }//GEN-LAST:event_jtf_cuitFilterActionPerformed

    private void deselectClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deselectClientActionPerformed
        overviewReport();
        cleanAllFields();
    }//GEN-LAST:event_deselectClientActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deselectClient;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel_data;
    private javax.swing.JPanel jPanel_table;
    private javax.swing.JScrollPane jScrollPaneTabla;
    private javax.swing.JLabel jbl_filter;
    private javax.swing.JLabel jbl_reportDataLine0;
    private javax.swing.JLabel jbl_reportDataLine1;
    private javax.swing.JLabel jbl_reportDataLine2;
    private javax.swing.JLabel jbl_reportDataLine3;
    private javax.swing.JLabel jbl_reportDataLine4;
    private javax.swing.JLabel jbl_reportDataLine5;
    private javax.swing.JLabel jbl_reportDataLine6;
    private javax.swing.JLabel jbl_reportDataLine7;
    private javax.swing.JLabel jbl_reportDataLine8;
    private javax.swing.JLabel jbl_reportDataLine9;
    private javax.swing.JLabel jbl_reportTitle;
    private javax.swing.JTextField jtf_cuitFilter;
    private javax.swing.JTable tableClient;
    // End of variables declaration//GEN-END:variables

    @Override
    public void initValidator() {
    }

    @Override
    public void initListener() {
        tableClient.getSelectionModel().addListSelectionListener(new TableListener(this));
        jtf_cuitFilter.getDocument().addDocumentListener(new JTextFieldListener(this));
    }

    @Override
    public void initPanel() {
        if (!lines.isEmpty()) {
            lines.clear();
        }
        jbl_reportDataLine1.setText("");
        lines.add(jbl_reportDataLine1);
        jbl_reportDataLine2.setText("");
        lines.add(jbl_reportDataLine2);
        jbl_reportDataLine3.setText("");
        lines.add(jbl_reportDataLine3);
        jbl_reportDataLine4.setText("");
        lines.add(jbl_reportDataLine4);
        jbl_reportDataLine5.setText("");
        lines.add(jbl_reportDataLine5);
        jbl_reportDataLine6.setText("");
        lines.add(jbl_reportDataLine6);
        jbl_reportDataLine7.setText("");
        lines.add(jbl_reportDataLine7);
        jbl_reportDataLine8.setText("");
        lines.add(jbl_reportDataLine8);
        jbl_reportDataLine9.setText("");
        lines.add(jbl_reportDataLine9);
        jbl_reportDataLine0.setText("");
        lines.add(jbl_reportDataLine0);
    }

    @Override
    public JTable getTable() {
        return tableClient;
    }

    @Override
    public void selectFromTable() {
        int field = tableClient.getSelectedRow();
        if (field >= 0) {
            Client client = clients.get(field);
            this.clients = panel.updateClientsTable(client.getCuit());
            clientReport(client);
        }
    }

    @Override
    public void changeConditionAllFields(boolean state) {
    }

    @Override
    public void changeConditionField(JTextField textField, boolean state) {
    }

    @Override
    public void changeConditionAllButtons(boolean state) {
    }

    @Override
    public void changeConditionButton(JButton button, boolean state) {
    }

    @Override
    public void cleanAllFields() {
        jtf_cuitFilter.setText("");
    }

    @Override
    public void cleanField(JTextField textfield) {
    }

    @Override
    public boolean verifyEmptyFields() {
        return false;
    }

    @Override
    public String getStringFilter() {
        return "";
    }

    @Override
    public void updateTable() {
        this.clients = this.panel.updateClientsTable(jtf_cuitFilter.getText());
    }

    @Override
    public JTable getClientsTable() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public JTable getProductsTable() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public JTable getWarehousesTable() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public JTable getSectorsTable() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public JTable getOrdersTable() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public JTable getCarriersTable() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public JTable getDetailOrdersTable() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public String getClientFilter() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public String getProductFilter() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public String getWarehouseFilter() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public String getSectorFilter() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public String getOrderFilter() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public String getCarrierFilter() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void overviewReport() {
        initPanel();
        this.clients = panel.updateClientsTable("");
        jbl_reportTitle.setText("INFORME GENERAL:");
        String report = panel.clientOverviewReport();
        String auxiliar = "";
        int count = 0;
        for (int i = 0; i < report.length(); i++) {
            auxiliar += report.charAt(i);
            if (report.charAt(i) == '.' || report.charAt(i) == ':') {
                if (!Character.isDigit(report.charAt(i - 1))) {
                    lines.get(count).setText(auxiliar);
                    auxiliar = "";
                    count++;
                }
            }
        }
    }

    private void clientReport(Client client) {
        initPanel();
        this.clients = panel.updateClientsTable(client.getCuit());
        String report = panel.clientReport(client);
        jbl_reportTitle.setText("INFORME DE " + client.getLastname() + " " + client.getName() + ":");
        String auxiliar = "";
        int count = 0;
        for (int i = 0; i < report.length(); i++) {
            auxiliar += report.charAt(i);
            if (report.charAt(i) == '.' || report.charAt(i) == ':') {
                if (!Character.isDigit(report.charAt(i - 1))) {
                    lines.get(count).setText(auxiliar);
                    auxiliar = "";
                    count++;
                }
            }
        }
    }

}
