package com.itec1.e_commerce.views;

import com.itec1.e_commerce.controllers.ReportPanelController;
import com.itec1.e_commerce.entities.Product;
import com.itec1.e_commerce.entities.Provider;
import com.itec1.e_commerce.views.resources.FieldDataValidator;
import com.itec1.e_commerce.views.resources.JTextFieldListener;
import com.itec1.e_commerce.views.resources.TableListener;

import java.awt.*;
import java.util.List;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sjcex
 */
public class Report_ProvidersPanel extends javax.swing.JPanel implements InterfacePanel {

    private final ReportPanelController panel;
    private final FieldDataValidator validator;
    private List<Provider> providers;
    private List<Product> products;

    /**
     * Creates new form Management_Client_Panel
     */
    public Report_ProvidersPanel() {
        initComponents();
        this.panel = new ReportPanelController(this);
        this.validator = new FieldDataValidator();
        initListener();
        initValidator();
        initPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel_data = new javax.swing.JPanel();
        jbl_reportTitle = new javax.swing.JLabel();
        jbl_reportTitle1 = new javax.swing.JLabel();
        jbl_reportTitle2 = new javax.swing.JLabel();
        jbl_reportTitle5 = new javax.swing.JLabel();
        jbl_reportTitle4 = new javax.swing.JLabel();
        jScrollPaneTabla1 = new javax.swing.JScrollPane();
        tbl_top_products = new javax.swing.JTable();
        jbl_reportTitle6 = new javax.swing.JLabel();
        jtf_total_proveedores = new javax.swing.JTextField();
        jtf_total_habilitados = new javax.swing.JTextField();
        jtf_valoracion = new javax.swing.JTextField();
        jPanel_table = new javax.swing.JPanel();
        jScrollPaneTabla = new javax.swing.JScrollPane();
        tbl_providers = new javax.swing.JTable();
        jbl_filter = new javax.swing.JLabel();
        jtf_cuit_filter = new javax.swing.JTextField();
        btn_select = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(800, 600));
        jPanel2.setMinimumSize(new java.awt.Dimension(800, 600));

        jPanel_data.setBackground(new java.awt.Color(0, 51, 255));

        jbl_reportTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbl_reportTitle.setForeground(new java.awt.Color(255, 255, 255));
        jbl_reportTitle.setText("INFORME GENERAL:");

        jbl_reportTitle1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbl_reportTitle1.setForeground(new java.awt.Color(255, 255, 255));
        jbl_reportTitle1.setText("Total de Proveedores:");

        jbl_reportTitle2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbl_reportTitle2.setForeground(new java.awt.Color(255, 255, 255));
        jbl_reportTitle2.setText("Habilitados:");

        jbl_reportTitle5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbl_reportTitle5.setForeground(new java.awt.Color(255, 255, 255));
        jbl_reportTitle5.setText("PROVEEDOR SELECCIONADO:");

        jbl_reportTitle4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbl_reportTitle4.setForeground(new java.awt.Color(255, 255, 255));
        jbl_reportTitle4.setText("Valoracion:");

        jScrollPaneTabla1.setMaximumSize(new java.awt.Dimension(950, 750));
        jScrollPaneTabla1.setMinimumSize(new java.awt.Dimension(950, 750));
        jScrollPaneTabla1.setPreferredSize(new java.awt.Dimension(950, 750));

        tbl_top_products.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tbl_top_products.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPaneTabla1.setViewportView(tbl_top_products);

        jbl_reportTitle6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbl_reportTitle6.setForeground(new java.awt.Color(255, 255, 255));
        jbl_reportTitle6.setText("TOP 10 PRODUCTOS");

        jtf_total_proveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_total_proveedoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_dataLayout = new javax.swing.GroupLayout(jPanel_data);
        jPanel_data.setLayout(jPanel_dataLayout);
        jPanel_dataLayout.setHorizontalGroup(
            jPanel_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_dataLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_dataLayout.createSequentialGroup()
                        .addGroup(jPanel_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbl_reportTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbl_reportTitle5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel_dataLayout.createSequentialGroup()
                                .addGroup(jPanel_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbl_reportTitle2)
                                    .addComponent(jbl_reportTitle1))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtf_total_proveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtf_total_habilitados, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel_dataLayout.createSequentialGroup()
                        .addComponent(jbl_reportTitle4, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jtf_valoracion, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(172, 172, 172)))
                .addGroup(jPanel_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_dataLayout.createSequentialGroup()
                        .addComponent(jbl_reportTitle6)
                        .addGap(158, 158, 158))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_dataLayout.createSequentialGroup()
                        .addComponent(jScrollPaneTabla1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
        );
        jPanel_dataLayout.setVerticalGroup(
            jPanel_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_dataLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbl_reportTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbl_reportTitle6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbl_reportTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtf_total_proveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbl_reportTitle2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtf_total_habilitados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(jbl_reportTitle5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbl_reportTitle4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtf_valoracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(134, 134, 134))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_dataLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPaneTabla1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanel_table.setBackground(new java.awt.Color(0, 51, 255));

        jScrollPaneTabla.setMaximumSize(new java.awt.Dimension(950, 750));
        jScrollPaneTabla.setMinimumSize(new java.awt.Dimension(950, 750));
        jScrollPaneTabla.setPreferredSize(new java.awt.Dimension(950, 750));

        tbl_providers.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tbl_providers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPaneTabla.setViewportView(tbl_providers);

        jbl_filter.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbl_filter.setForeground(new java.awt.Color(255, 255, 255));
        jbl_filter.setText("Filtrar por cuit:");

        jtf_cuit_filter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtf_cuit_filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_cuit_filterActionPerformed(evt);
            }
        });

        btn_select.setText("Seleccionar");
        btn_select.setMaximumSize(new java.awt.Dimension(110, 23));
        btn_select.setMinimumSize(new java.awt.Dimension(110, 23));
        btn_select.setPreferredSize(new java.awt.Dimension(110, 23));
        btn_select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_selectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_tableLayout = new javax.swing.GroupLayout(jPanel_table);
        jPanel_table.setLayout(jPanel_tableLayout);
        jPanel_tableLayout.setHorizontalGroup(
            jPanel_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_tableLayout.createSequentialGroup()
                .addGroup(jPanel_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_tableLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbl_filter, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtf_cuit_filter, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_select, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_tableLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPaneTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel_tableLayout.setVerticalGroup(
            jPanel_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_tableLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPaneTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(jPanel_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_select, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_cuit_filter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbl_filter, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_table, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_data, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel_table, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_cuit_filterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_cuit_filterActionPerformed
        providers = panel.updateProvidersTable(jtf_cuit_filter.getText());
    }//GEN-LAST:event_jtf_cuit_filterActionPerformed

    private void jtf_total_proveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_total_proveedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_total_proveedoresActionPerformed

    private void btn_selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_selectActionPerformed
        if (btn_select.getText().equals("Seleccionar")) {
            jtf_cuit_filter.setEnabled(false);
            jtf_cuit_filter.setText(tbl_providers.getValueAt(tbl_providers.getSelectedRow(), 2).toString());
            tbl_providers.setEnabled(false);
            getTopProductsTable(jtf_cuit_filter.getText());
            jtf_valoracion.setText(getValoracion());
            btn_select.setText("Limpiar");
        } else {
            jtf_cuit_filter.setText("");
            jtf_valoracion.setText("");
            jtf_cuit_filter.setEnabled(true);
            tbl_providers.setEnabled(true);
            clearProductsTable();
            btn_select.setEnabled(false);
            btn_select.setText("Seleccionar");
        }
    }//GEN-LAST:event_btn_selectActionPerformed

    private void clearProductsTable() {
        DefaultTableModel model = (DefaultTableModel) tbl_top_products.getModel();
        model.setRowCount(0);
        tbl_top_products.setModel(model);
    }

    private String getValoracion() {
        Integer score = panel.getScore(jtf_cuit_filter.getText());
        return score.toString();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_select;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel_data;
    private javax.swing.JPanel jPanel_table;
    private javax.swing.JScrollPane jScrollPaneTabla;
    private javax.swing.JScrollPane jScrollPaneTabla1;
    private javax.swing.JLabel jbl_filter;
    private javax.swing.JLabel jbl_reportTitle;
    private javax.swing.JLabel jbl_reportTitle1;
    private javax.swing.JLabel jbl_reportTitle2;
    private javax.swing.JLabel jbl_reportTitle4;
    private javax.swing.JLabel jbl_reportTitle5;
    private javax.swing.JLabel jbl_reportTitle6;
    private javax.swing.JTextField jtf_cuit_filter;
    private javax.swing.JTextField jtf_total_habilitados;
    private javax.swing.JTextField jtf_total_proveedores;
    private javax.swing.JTextField jtf_valoracion;
    private javax.swing.JTable tbl_providers;
    private javax.swing.JTable tbl_top_products;
    // End of variables declaration//GEN-END:variables

    @Override
    public void initValidator() {
        validator.onlyNumbers(jtf_cuit_filter);
    }

    @Override
    public void initListener() {
        jtf_cuit_filter.getDocument().addDocumentListener(new JTextFieldListener<>(this));
        tbl_providers.getSelectionModel().addListSelectionListener(new TableListener(this));
    }

    @Override
    public void initPanel() {
        this.panel.updateProvidersTable("");
        btn_select.setPreferredSize(new Dimension(110, 23));
        btn_select.setText("Seleccionar");
        btn_select.setEnabled(false);
        jtf_total_proveedores.setEnabled(false);
        jtf_total_proveedores.setText(getTotalProveedores());
        jtf_total_habilitados.setText(getTotalHabilitados());
        jtf_total_habilitados.setEnabled(false);
        jtf_valoracion.setEnabled(false);
        tbl_top_products.setEnabled(false);
    }

    private String getTotalHabilitados() {
        Integer total = panel.getTotalEnabledProviders();
        if (total == null) {
            return "0";
        }
        return total.toString();
    }

    private String getTotalProveedores() {
        Integer total = panel.getTotalProviders();
        if (total == null) {
            return "0";
        }
        return total.toString();
    }

    @Override
    public JTable getTable() {
        return this.tbl_providers;
    }

    @Override
    public void selectFromTable() {
        btn_select.setEnabled(true);
    }

    @Override
    public void changeConditionAllFields(boolean state) {
    }

    @Override
    public void changeConditionField(JTextField textField, boolean state) {
    }

    @Override
    public void changeConditionAllButtons(boolean state) {
    }

    @Override
    public void changeConditionButton(JButton button, boolean state) {
    }

    @Override
    public void cleanAllFields() {
        jtf_cuit_filter.setText("");
    }

    @Override
    public void cleanField(JTextField textfield) {
    }

    @Override
    public boolean verifyEmptyFields() {
        return false;
    }

    @Override
    public String getStringFilter() {
        return "";
    }

    @Override
    public void updateTable() {
        providers = panel.updateProvidersTable(jtf_cuit_filter.getText());
    }

    public void getTopProductsTable(String cuit) {
        tbl_top_products.setModel(panel.loadTopProducts( cuit ));
    }

}
